# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog 1
subtitle: Random Talk on Random Thoughts
author: Vincent Tam
simple_search: https://google.com/search
email: your-email@domain.com
category_feeds: true
description: My memory dump, code bin, and space for posting LaTeX math
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vincenttam.github.io" # the base hostname & protocol for your site, e.g. http://example.com
myurl: "https://vincenttam.github.io"
permalink: /blog/:year/:month/:day/:title/
category_dir: blog/categories

paginate: 10          # Posts per page on the blog index
paginate_path: "posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
date_format: 'ordinal'
time_format:  '%-I:%M %P'
timezone: Asia/Hong_Kong

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
blog_index_asides: [custom/asides/about.html, custom/asides/category_list.html, asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
post_asides: [custom/asides/about.html, custom/asides/category_list.html, asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
page_asides: [custom/asides/about.html, custom/asides/category_list.html, asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

permalink_label: "&infin;"
permalink_label_feed: "&infin; Permalink"
linklog_marker: "&#9733;"

# 3rd party settings
twitter_username: jekyllrb
github_username:  VincentTam
# Disqus Comments
disqus_short_name: blogueun
disqus_show_comment_count: true
# Google Analytics
google_analytics_tracking_id: UA-46788371-2

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle
  - bin
  - vendor
  - bower_components
  - bower.json
# sass custom load path
# re: https://github.com/jekyll/jekyll-help/issues/98
sass:
    sass_dir: sass
    load_paths:
      - bower_components/compass-mixins/lib/
